DROP DATABASE IF EXISTS human_friends;
CREATE DATABASE human_friends;
USE human_friends;

# parent table: animals
DROP TABLE IF EXISTS animals;
CREATE TABLE animals(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	# PRIMARY KEY +- = UNIQUE | PRIMARY KEY creates clasteries index
	# id2 SERIAL # BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE
	animal_type VARCHAR(100) UNIQUE
);


# child tables: pets, packs
DROP TABLE IF EXISTS pets;
CREATE TABLE pets(
	animal_id BIGINT UNSIGNED NOT NULL,
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	pet_type VARCHAR(100)
);

ALTER TABLE pets ADD CONSTRAINT fk_pets_animal_id
FOREIGN KEY (animal_id) REFERENCES animals(id);


DROP TABLE IF EXISTS packs;
CREATE TABLE packs(
	animal_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (animal_id) REFERENCES animals(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	pack_type VARCHAR(100)
);

# child tables: pets
DROP TABLE IF EXISTS dogs;
CREATE TABLE dogs(
	pet_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pet_id) REFERENCES pets(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);

DROP TABLE IF EXISTS cats;
CREATE TABLE cats(
	pet_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pet_id) REFERENCES pets(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);

DROP TABLE IF EXISTS hamsters;
CREATE TABLE hamsters(
	pet_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pet_id) REFERENCES pets(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);

#child tables: packs

DROP TABLE IF EXISTS horses;
CREATE TABLE horses(
	pack_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pack_id) REFERENCES packs(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);

DROP TABLE IF EXISTS camels;
CREATE TABLE camels(
	pack_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pack_id) REFERENCES packs(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);

DROP TABLE IF EXISTS donkeys;
CREATE TABLE donkeys(
	pack_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pack_id) REFERENCES packs(id),
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME DEFAULT NOW(),
	name VARCHAR(100),
	birthday DATE,
	command VARCHAR(100)
);



